name: Build and Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    
    - name: Install .NET Framework 4.6 Targeting Pack
      run: choco install netfx-4.6-targetpack --confirm
    
    - name: Install Dokan
      run: |
        $dokanUrl = "https://github.com/dokan-dev/dokany/releases/download/v2.3.0.1000/Dokan_x64.msi"
        $installerPath = "$env:TEMP\Dokan_x64.msi"
        Invoke-WebRequest -Uri $dokanUrl -OutFile $installerPath
        msiexec /i "$installerPath" /quiet /qn /norestart
        Start-Sleep -Seconds 10
        
        # Verify installation
        if (Test-Path "C:\Program Files\Dokan\Dokan Library-2.3.0.1000") {
          echo "Dokan installed successfully"
        } else {
          echo "Dokan installation failed"
          exit 1
        }
    
    - name: Restore NuGet packages
      run: nuget restore Dokan2.Archive.sln
    
    - name: Build Solution (x64 Release)
      run: msbuild Dokan2.Archive.sln /p:Configuration=Release /p:Platform=x64 /p:DeployOnBuild=true
