name: Build and Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup VS MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Build
      run: msbuild Dokan2.Archive.sln -t:Build -property:Configuration=Release -property:Platform=x64
